serkantumkaya/studentservices

Nieuw tekstdocument.txt
proberen testbranche en master te koppelen
=> testbranche samenvoeging

Model/CategorieModel.php, Model/GebruikerModel.php, Model/OpleidingModel.php, Model/ProfielModel.php, Model/ProjectModel.php, Model/SchoolModel.php, README.md, View/Categorie/View.php, View/School/View.php
Bouwen aan de hand van instructies in de README
=> TODO gemaakt model en controller

Includes/DB.php, Nietcode/SQL/Compleet.sql, inlogPag.php
Salt toegevoegd aan wachtwoorden. DB gebruikers gedeelte opnieuw inladen, of alleen het wachtwoord veranderen, of de hele database
=> Pepper and salt

BaseClass/Feedback.php, BaseClass/Profiel.php, Controller/FeedbackController.php, Controller/GebruikerController.php, Controller/ProfielController.php, Model/FeedbackModel.php, View/Feedback/View.php, View/Gebruiker/Edit.php
functies:
getGemiddeldeGegevenScore(),
getGegevenFeedback()
get gekregen feedback en get gemiddeldeGekregenScore moeten nog
=> Feedback uitbreiden

BaseClass/Project.php, BaseClass/Projecten.php, Controller/ProfielController.php, Controller/ProjectController.php, Model/ProjectModel.php, index.php
Gedeelte van project wat serkan heeft gemaakt samenvoegen met de rest
=> Project toevoegen

ClientSide/Contact.php, ClientSide/contactformulier.js, Includes/header.php, Includes/menu.php, JS/script.js, css/style.css, inlogPag.php
Op Root niveau een folder aangemaakt -> ClientSide
In die folder heb ik "Contact.php" aangemaakt.
In die folder heb ik contactformulier.js aangemaakt (deze heb ik uit ons vorige project)
In de folder "Includes" heb ik "menu.php" aangemaakt.
header.php heb ik opgesplits -> een deel van header.php heb ik opgenomen in menu.php (hiermee zorgen we ervoor dat we sneller aanpassingen kunnen doorvoeren op alleen het menu en de menu items.
header.php bevat momenteel alle meta data, verwijzingen naar scripts en css etc.
header.php heeft een include van menu.php.
=> Contactpagina plus menu/header

BaseClass/Feedback.php, BaseClass/Project.php, ClientSide/Contact.php, Controller/FeedbackController.php, Controller/ProjectController.php, Includes/menu.php, Model/FeedbackModel.php, Model/ProjectModel.php, Nietcode/SQL/Compleet.sql, View/Categorie/Edit.php, View/Feedback/View.php, View/Project/Add.php, View/Project/Edit.php, View/Project/View.php
Feedback en project klaargemaakt
functie om gemiddelde gegeven en gekregen score te bekijken aan de hand va nGebruikerID
SQL bijgewerkt
=> Project&feedback jelle

BaseClass/Reactie.php, BaseClass/tijdeijk.php, ClientSide/Project.php, Controller/ReactieController.php, Nietcode/SQL/Compleet.sql, css/Projecten.css
stukje styling, alle onderdelen zij nu te zien op Project.php
=> styling project

ClientSide/Project.php, ClientSide/Projecten.php, Includes/menu.php, View/Project/Client/detail.php, View/Project/Client/gebruikerAdd.php, View/Project/Client/gebruikerChange.php, css/Projecten.css
=> Project opsplitsen

BaseClass/Project.php, ClientSide/Projecten.php, Controller/ProjectController.php, Model/ProjectModel.php, Nietcode/SQL/Compleet.sql, View/Project/Client/detail.php, View/Project/Client/gebruikerAdd.php, View/Project/Client/gebruikerChange.php, View/Project/Edit.php, css/Projecten.css
Je kan nu zoeken op "alleen mijn projectemn" of  alleen andere projecten.
parameters in de Sessie geduwd. maar kan de laatste waarde er niet uit krijgen
=> Project filtering uitgebreid

ClientSide/Projecten.php
werkt nu als je van pagina verspringt
meest erge kutgezeik tot nu toe
=> filtering bijgewerkt

ClientSide/Projecten.php, Controller/ProjectController.php, Includes/Translate/Translate.php, Includes/footer.php, Includes/menu.php, Model/ProjectModel.php
=> project vertaling, footer en header aanbassing

Controller/GebruikerController.php, JS/script.js, View/Profiel/Add.php, View/Profiel/Edit.php
=> Profiel met validatie

JS/script.js
=> overbodige script weg

Includes/header.php
=> Icoontje en inlogbeveiliging

Nietcode/SQL/Compleet.sql
Beschikbaarheid nu met ophogende ID en een unique index
=> Beschikbaarheid SQL

css/Homepage.css
=> fixes in homepage.css

BaseClass/ZoekOpdracht.php, ClientSide/Projecten.php, Controller/ProjectController.php, Controller/ZoekController.php, Includes/menu.php, Model/ProjectModel.php, Model/ZoekModel.php, View/Project/Zoek.php
admin kan zoekopdrachten opvragen en verwijderen
=> Admin verwijderen zoekopdrachten

ClientSide/Projecten.php, View/Project/Client/detail.php, View/Project/Client/gebruikerAdd.php, css/Projecten.css, css/style.css
hoop dat het goed is, kutwerk
syling van projecten, project, add en change aangepast
=> Styling mobile responsive gemaakt

BaseClass/Beschikbaarheid.php, Controller/BeschikbaarheidController.php, Controller/files/categorieen.csv, Controller/files/opleidingen.csv, Includes/Translate/Translate.php, Model/BeschikbaarheidModel.php, Nietcode/SQL/Compleet.sql, View/Beschikbaarheid/Add.php, View/Beschikbaarheid/Edit.php, View/Beschikbaarheid/View.php, View/Profiel/Add.php, View/Profiel/View.php, View/Project/Client/detail.php
=> Beschikbaarheid werkend

Controller/ProfielController.php, Includes/Translate/Translate.php, View/Beschikbaarheid/View.php, View/Project/Client/detail.php
Profiel overzicht en beschikbaarheidoverzicht
=> Profiel overzicht en beschikbaarheidoverzicht

css/Projecten.css
gezeik weer eens met die brannches
=> Projectpupup

ClientSide/Projecten.php, Includes/Translate/Translate.php, Unittest/unittestsample.php, View/Project/Client/detail.php, View/Project/Client/gebruikerAdd.php, View/Project/Client/gebruikerChange.php, css/Projecten.css
=> stukje styling, laatste dingen afgerond

Includes/menu.php, css/style.css
=> Menu weer werkend

BaseClass/Feedback.php
gebruikerscontroller in de feedback weggehaald
=> feedback bijgewerkt

Controller/HomepageController.php, Controller/files/opleidingen.csv, View/Homepagina/view.php, css/Homepage.css, css/Projecten.css, css/Veelgesteldevragen.css, css/style.css
styling FAQ en Dashboard aangepakt
=> Styling klaar

Includes/footer.php, View/Project/Client/detail.php, css/Homepage.css, css/Projecten.css
=> styling projecten

View/Project/Client/detail.php, View/Project/Client/gebruikerAdd.php, View/Project/Client/gebruikerChange.php, css/Projecten.css
=> Styling afgemaakt

Includes/menu.php, View/Categorie/Add.php, View/Categorie/Edit.php, View/Categorie/View.php, View/Gebruiker/Add.php, View/Gebruiker/Edit.php, View/Gebruiker/View.php, View/Opleiding/Add.php, View/Opleiding/Edit.php, View/Opleiding/View.php, View/School/Add.php, View/School/Edit.php, View/School/View.php
menu klaar schermen nog nalopen
=> menu klaar schermen nog nalopen

View/Feedback/Add.php, View/Feedback/Edit.php, View/Feedback/View.php, View/Project/Add.php, View/Project/Edit.php, View/Project/View.php, View/Reactie/Add.php, View/Reactie/Edit.php, View/Reactie/View.php
menu bijgewerkt voor zover bekent
=> menu bijgewerkt voor zover bekent
